# Generated by Django 5.1.4 on 2024-12-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='name',
            new_name='inputText',
        ),
        migrations.RemoveField(
            model_name='react',
            name='detail',
        ),
    ]
