# Generated by Django 5.1.4 on 2024-12-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_react_inputtext_remove_react_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='C:\\.Projects\\StudiesProjects\\InzynieriaProgramowania\\Projekt_Inzynieria_Oprogramowania\\backend\\uploads/')),
            ],
        ),
    ]
