# Generated by Django 5.1.4 on 2024-12-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_file_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='React',
            new_name='Text',
        ),
    ]
